namespace MappingSourceGenerator.UnitTests;

public static class GenericModelMappingTestData
{
    public static IEnumerable<object[]> Data
        => new[]
        {
            new object[]
            {
                "GenericModelMappingTestData.NestedGenericProperty",
                """
                #nullable enable
                using System;
                using System.Collections.Generic;
                using MappingSourceGenerator.Markers;

                namespace MappingSourceGenerator.UnitTests;

                public class GenericModelMappingTests
                {
                    public record PersonWithCar1<TCar>(
                        string Name,
                        TCar Car);
                
                    public record Car1(
                        string Model);
                
                    public record PersonWithCar2<TCar>(
                        string Name,
                        TCar Car);
                
                    public record Car2(
                        string Model);
                }

                public static partial class GenericModelMappingTestsMapper
                {
                    [GenerateMapping]
                    public static partial GenericModelMappingTests.PersonWithCar2<GenericModelMappingTests.Car2> Map(this GenericModelMappingTests.PersonWithCar1<GenericModelMappingTests.Car1> personWithCar1);
                }
                """,
                """
                // <auto-generated/>
                #pragma warning disable
                #nullable enable
                using System;
                using System.Linq;

                namespace MappingSourceGenerator.UnitTests;

                partial class GenericModelMappingTestsMapper
                {
                    public static MappingSourceGenerator.UnitTests.GenericModelMappingTests.Car2 Map(
                        this MappingSourceGenerator.UnitTests.GenericModelMappingTests.Car1 car1)
                        => new(
                            car1.Model);
                
                    public static partial MappingSourceGenerator.UnitTests.GenericModelMappingTests.PersonWithCar2<MappingSourceGenerator.UnitTests.GenericModelMappingTests.Car2> Map(
                        this MappingSourceGenerator.UnitTests.GenericModelMappingTests.PersonWithCar1<MappingSourceGenerator.UnitTests.GenericModelMappingTests.Car1> personWithCar1)
                        => new(
                            personWithCar1.Name,
                            personWithCar1.Car.Map());
                }
                """
            },
             new object[]
             {
                 "GenericModelMappingTestData.NestedGenericPropertyWithManualMapping",
                 """
                 #nullable enable
                 using System;
                 using System.Collections.Generic;
                 using MappingSourceGenerator.Markers;

                 namespace MappingSourceGenerator.UnitTests;

                 public class GenericModelMappingTests
                 {
                     public record PersonWithCar1<TCar>(
                         string Name,
                         TCar Car);
                 
                     public record ManualCar1(
                         string Model1);
                 
                     public record PersonWithCar2<TCar>(
                         string Name,
                         TCar Car);
                 
                     public record ManualCar2(
                         string Model2);
                 }

                 public static partial class GenericModelMappingTestsMapper
                 {
                     [GenerateMapping]
                     public static partial GenericModelMappingTests.PersonWithCar2<GenericModelMappingTests.ManualCar2> Map(
                        this GenericModelMappingTests.PersonWithCar1<GenericModelMappingTests.ManualCar1> personWithCar1);
                 
                     public static GenericModelMappingTests.ManualCar2 Map(
                         this GenericModelMappingTests.ManualCar1 manualCar1)
                         => new(
                             manualCar1.Model1);
                 }
                 """,
                 """
                 // <auto-generated/>
                 #pragma warning disable
                 #nullable enable
                 using System;
                 using System.Linq;

                 namespace MappingSourceGenerator.UnitTests;

                 partial class GenericModelMappingTestsMapper
                 {
                     public static partial MappingSourceGenerator.UnitTests.GenericModelMappingTests.PersonWithCar2<MappingSourceGenerator.UnitTests.GenericModelMappingTests.ManualCar2> Map(
                         this MappingSourceGenerator.UnitTests.GenericModelMappingTests.PersonWithCar1<MappingSourceGenerator.UnitTests.GenericModelMappingTests.ManualCar1> personWithCar1)
                         => new(
                             personWithCar1.Name,
                             personWithCar1.Car.Map());
                 }
                 """
             },
        };
}