namespace MappingSourceGenerator.UnitTests;

public static class GenericModelTestData
{
    public static IEnumerable<object[]> Data
        => new[]
        {
            new object[]
            {
                "GenericModel.NestedGenericProperty",
                """
                #nullable enable
                using System;
                using System.Collections.Generic;
                using MappingSourceGenerator.Markers;

                namespace MappingSourceGenerator.UnitTests;

                public class GenericModelTests
                {
                    public record PersonWithCar1<TCar>(
                        string Name,
                        TCar Car);
                
                    public record Car1(
                        string Model);
                
                    public record PersonWithCar2<TCar>(
                        string Name,
                        TCar Car);
                
                    public record Car2(
                        string Model);
                }

                public static partial class GenericModelTestsMapper
                {
                    [GenerateMapping]
                    public static partial GenericModelTests.PersonWithCar2<GenericModelTests.Car2> Map(this GenericModelTests.PersonWithCar1<GenericModelTests.Car1> personWithCar1);
                }
                """,
                """
                // <auto-generated/>
                #pragma warning disable
                #nullable enable
                using System;
                using System.Linq;

                namespace MappingSourceGenerator.UnitTests;

                partial class GenericModelTestsMapper
                {
                    public static MappingSourceGenerator.UnitTests.GenericModelTests.Car2 Map(
                        this MappingSourceGenerator.UnitTests.GenericModelTests.Car1 car1)
                        => new(
                            car1.Model);
                
                    public static partial MappingSourceGenerator.UnitTests.GenericModelTests.PersonWithCar2<MappingSourceGenerator.UnitTests.GenericModelTests.Car2> Map(
                        this MappingSourceGenerator.UnitTests.GenericModelTests.PersonWithCar1<MappingSourceGenerator.UnitTests.GenericModelTests.Car1> personWithCar1)
                        => new(
                            personWithCar1.Name,
                            personWithCar1.Car.Map());
                }
                """
            },
             new object[]
             {
                 "GenericModel.NestedGenericPropertyWithManualMapping",
                 """
                 #nullable enable
                 using System;
                 using System.Collections.Generic;
                 using MappingSourceGenerator.Markers;

                 namespace MappingSourceGenerator.UnitTests;

                 public class GenericModelTests
                 {
                     public record PersonWithCar1<TCar>(
                         string Name,
                         TCar Car);
                 
                     public record ManualCar1(
                         string Model1);
                 
                     public record PersonWithCar2<TCar>(
                         string Name,
                         TCar Car);
                 
                     public record ManualCar2(
                         string Model2);
                 }

                 public static partial class GenericModelTestsMapper
                 {
                     [GenerateMapping]
                     public static partial GenericModelTests.PersonWithCar2<GenericModelTests.ManualCar2> Map(
                        this GenericModelTests.PersonWithCar1<GenericModelTests.ManualCar1> personWithCar1);
                 
                     public static GenericModelTests.ManualCar2 Map(
                         this GenericModelTests.ManualCar1 manualCar1)
                         => new(
                             manualCar1.Model1);
                 }
                 """,
                 """
                 // <auto-generated/>
                 #pragma warning disable
                 #nullable enable
                 using System;
                 using System.Linq;

                 namespace MappingSourceGenerator.UnitTests;

                 partial class GenericModelTestsMapper
                 {
                     public static partial MappingSourceGenerator.UnitTests.GenericModelTests.PersonWithCar2<MappingSourceGenerator.UnitTests.GenericModelTests.ManualCar2> Map(
                         this MappingSourceGenerator.UnitTests.GenericModelTests.PersonWithCar1<MappingSourceGenerator.UnitTests.GenericModelTests.ManualCar1> personWithCar1)
                         => new(
                             personWithCar1.Name,
                             personWithCar1.Car.Map());
                 }
                 """
             },
        };
}