namespace MappingSourceGenerator.UnitTests;

public static class NonNestedClassTestData
{
    public static IEnumerable<object[]> Data
        => new[]
        {
            new object[]
            {
                "NonNestedClassAndEnumMappingTest",
                """
                #nullable enable
                using System.Collections.Generic;
                using System.Linq;
                using MappingSourceGenerator.Markers;

                namespace MappingSourceGenerator.UnitTests;
                
                public record PersonWithPhoneType1(
                    string Name,
                    PhoneType1 PhoneType);

                public record PersonWithPhoneType2(
                    string Name,
                    PhoneType2 PhoneType);

                public enum PhoneType1
                {
                    Android,
                    Ios,
                    Other,
                }

                public enum PhoneType2
                {
                    Android,
                    Ios,
                    Other,
                }

                public static partial class NonNestedClassTestsMapper
                {
                    [GenerateMapping]
                    public static partial PersonWithPhoneType2 Map(this PersonWithPhoneType1 personWithPhoneType1);
                }
                """,
                """
                // <auto-generated/>
                #pragma warning disable
                #nullable enable
                using System;
                using System.Linq;

                namespace MappingSourceGenerator.UnitTests;

                partial class NonNestedClassTestsMapper
                {
                    public static MappingSourceGenerator.UnitTests.PhoneType2 Map(
                        this MappingSourceGenerator.UnitTests.PhoneType1 phoneType1)
                        => phoneType1 switch
                        {
                            MappingSourceGenerator.UnitTests.PhoneType1.Android => MappingSourceGenerator.UnitTests.PhoneType2.Android,
                            MappingSourceGenerator.UnitTests.PhoneType1.Ios => MappingSourceGenerator.UnitTests.PhoneType2.Ios,
                            MappingSourceGenerator.UnitTests.PhoneType1.Other => MappingSourceGenerator.UnitTests.PhoneType2.Other,
                            _ => throw new InvalidOperationException($"Unable to map MappingSourceGenerator.UnitTests.PhoneType1.{phoneType1}"),
                        };

                    public static partial MappingSourceGenerator.UnitTests.PersonWithPhoneType2 Map(
                        this MappingSourceGenerator.UnitTests.PersonWithPhoneType1 personWithPhoneType1)
                        => new(
                            personWithPhoneType1.Name,
                            personWithPhoneType1.PhoneType.Map());
                }
                """
            }
        };
}